### ISSUE TITLE
Delay before pausing

### ISSUE THREAD

**Issue by SkYNewZ** [knative-sandbox/container-freezer#43]
Would it be possible, now or in the near future, to specify a delay between the last request to the pod and its pause? This would be to avoid unnecessary successive pause/unpause in case of batch for example.

**Comment by psschwei** [comment]
It's definitely doable (and something we were planning), though I think it'll be handled in Knative Serving rather than here.
/assign

**Comment by SkYNewZ** [comment]
Thanks for this quick reply. Would you like me to create the issue at Knative serving?

**Comment by psschwei** [comment]
No, I think it's fine here.

**Comment by kiemtcb** [comment]
hi, my container is an image processing application, it takes 30s to start up. However I see "queue-proxy" container launches immediately so it make pod goes to a frozen state while my container hasn't started up yet. 
i used the readinessprobe for my container so that the pod is not ready 2/2, but the "queue-proxy" container runs up and pod goes to freeze while the pod is only ready 1/2

**Comment by kiemtcb** [comment]
> /lifecycle frozen

hi, my container is an image processing application, it takes 30s to start up. However I see "queue-proxy" container launches immediately so it make pod goes to a frozen state while my container hasn't started up yet. 
i used the readinessprobe for my container so that the pod is not ready 2/2, but the "queue-proxy" container runs up and pod goes to freeze while the pod is only ready 1/2

**Comment by psschwei** [comment]
@kiemtcb as [all pods are initially frozen](https://github.com/knative/serving/blob/aaa992e30bee5e714e640c0fa0c9f3601fe3818f/pkg/queue/sharedmain/main.go#L379-L380). you might unfortunately have found a scenario where the freezer's default behavior isn't ideal...

**Comment by psschwei** [comment]
Closing this as we're archiving this repo (as discussed in #217 )
